version: "3.8"

services:
  mariadb :
    build : requirements/mariadb
    image : mariadb
    container_name : mariadb
    expose:
      - "3306"
    volumes :
      - db_data:/var/lib/mysql
    networks :
      - inception

  wordpress:
    image : wordpress
    container_name: wordpress
    build: requirements/wordpress
    depends_on : 
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
  
  nginx:
    image: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  wp_data:
    driver_opts:
      type : local
      device: /home/rlabbiz/data/wordpress
      o: bind

  db_data: 
    driver_opts:
      type : local
      device: /home/rlabbiz/data/database
      o: bind


networks:
  inception : 
    name: inception