version: "3.8"

services:
  mariadb :
    build : requirements/mariadb
    image : mariadb
    container_name : mariadb
    env_file :
      - .env
    expose:
      - "3306"
    volumes :
      - db_data:/var/lib/mysql
    networks :
      - inception
    restart: always

  wordpress:
    image : wordpress
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    depends_on :
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
  
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    depends_on :
      - wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

volumes:
  wp_data:
    driver_opts:
      type : local
      device: /home/rlabbiz/data/wordpress
      o: bind

  db_data: 
    driver_opts:
      type : local
      device: /home/rlabbiz/data/database
      o: bind


networks:
  inception:
    driver: bridge
