version: "3.8"

services:
  mariadb :
    build : requirements/mariadb
    image : mariadb:db
    container_name : mariadb
    volumes :
      - db_data:/var/lib/mysql
    networks :
      - inception

  wordpress:
    build: requirements/wordpress
    depends_on : 
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

volumes:
  wp_data:
    driver_opts:
      type : local
      device: /home/reda/data/wordpress
      o: bind

  db_data: 
    driver_opts:
      type : local
      device: /home/reda/data/database
      o: bind

networks:
  inception : 
    name: inception