version: "3.8"
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/rlabbiz/database
      o: bind

services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    build: requirements/wordpress
    volumes:
      - mariadb:/var/lib/mysql
  